# Generated by Django 5.2.1 on 2025-05-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_company_description_company_last_audit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_audit',
        ),
    ]
