# Generated by Django 5.2.1 on 2025-05-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
