# Generated by Django 5.2.1 on 2025-05-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_company_address_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interactions/')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.interaction')),
            ],
        ),
    ]
