# Generated by Django 5.2.1 on 2025-05-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_fileattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='files',
        ),
        migrations.CreateModel(
            name='InteractionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interactions/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='audits.interaction')),
            ],
        ),
    ]
