# Generated by Django 5.2.1 on 2025-05-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_remove_interaction_files_interactionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='interactions/'),
        ),
        migrations.DeleteModel(
            name='InteractionFile',
        ),
    ]
