# Generated by Django 5.2.1 on 2025-05-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
